// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYVgk-_0x2e2bdLcC1bMYzLbDDq0FZr-0',
    appId: '1:220867692338:web:ce740af6882d78e64a392b',
    messagingSenderId: '220867692338',
    projectId: 'carenest-84e01',
    authDomain: 'carenest-84e01.firebaseapp.com',
    storageBucket: 'carenest-84e01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIRIPHJqyyphE3HLcqjMSKolcN2YUpU1s',
    appId: '1:220867692338:android:c0eba49397e520ea4a392b',
    messagingSenderId: '220867692338',
    projectId: 'carenest-84e01',
    storageBucket: 'carenest-84e01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyk50gLY_o3aYQEU44-SdyJ4uwgir85o8',
    appId: '1:220867692338:ios:dba5c49d6030b36f4a392b',
    messagingSenderId: '220867692338',
    projectId: 'carenest-84e01',
    storageBucket: 'carenest-84e01.firebasestorage.app',
    iosBundleId: 'com.example.smartguideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyk50gLY_o3aYQEU44-SdyJ4uwgir85o8',
    appId: '1:220867692338:ios:dba5c49d6030b36f4a392b',
    messagingSenderId: '220867692338',
    projectId: 'carenest-84e01',
    storageBucket: 'carenest-84e01.firebasestorage.app',
    iosBundleId: 'com.example.smartguideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYVgk-_0x2e2bdLcC1bMYzLbDDq0FZr-0',
    appId: '1:220867692338:web:b856e458d69d17994a392b',
    messagingSenderId: '220867692338',
    projectId: 'carenest-84e01',
    authDomain: 'carenest-84e01.firebaseapp.com',
    storageBucket: 'carenest-84e01.firebasestorage.app',
  );

}